# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedisplay',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
