# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20181003_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedisplay',
            name='Display',
            field=models.BooleanField(default=False),
        ),
    ]
