# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_imagedisplay_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedisplay',
            name='Url',
            field=models.URLField(blank=True),
        ),
    ]
