# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-03 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_imagedisplay_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagedisplay',
            name='Url',
        ),
    ]
